### ISSUE TITLE
Cannot Launch Visual Studio Code

### ISSUE THREAD

**Issue by yegender124001** [sebanc/brioche#13]
Hi @sebanc , I have installed Chrome OS. I have installed brunch-toolchain and brioche also. Then I download Visual Studio Code. It Successfully installed. When I used the command `code` in the brioche shell. No response, Then I find that I should use `brioche ubuntu app code`. I also used this but no response again. Please help me. I need this program because I have to complete my coding project today. Please Help Me.

**Comment by sebanc** [comment]
run "brioche ubuntu app code --verbose" (it's in the readme known issues part)

**Comment by yegender124001** [comment]
I tried this but didn't work. Then I found that container get some damage. Then I create a new container then is run.

THanks
