### ISSUE TITLE
What to answer to `reset: unknown terminal type xterm-256color`?

### ISSUE THREAD

**Issue by mjarkk** [sebanc/brioche#3]
I wanted to setup this tool but i do not exactly know what to answer to this question: 
```
crosh> shell
chronos@localhost / $ brioche mycontainer create
reset: unknown terminal type xterm-256color
Terminal type? 
```
What is a correct terminal type i can fill in here to continue?

**Comment by sebanc** [comment]
Have you installed the brunch-toolchain ? Which brunch version are you on ?

**Comment by mjarkk** [comment]
> Have you installed the brunch-toolchain ?
Yup just installed it, also added `start-toolchain` to my bashrc

> Which brunch version are you on ?
```sh
chronos@localhost / $ cat /etc/brunch_version
Brunch r86 k4.19 20201014
```

**Comment by sebanc** [comment]
Well I have no idea what could be wrong here, the terminal type is part of ncurses if I am not mistaken and "xterm-256color" is the correct type.

Could you try removing "start-toolchain" from your bashrc, reboot and try again ?

**Comment by mjarkk** [comment]
Oh maybe i also need to note that i've probably used the wrong recovery image to setup brunch.  
I have used the eve (google pixelbook) recovery image but i think i should have used rammus as most people seem to use that one.

**Comment by mjarkk** [comment]
Hmm i think it's not related to this tool.  
Almost all command i run like `clear, nano, vim` return with the error message `'xterm-256color': unknown terminal type.`  

I also just remembered that i had installed chromebrew before installing brunch-toolchain and now everything doesn't work so there might have been a conflict there.  
Guess i have to reset my installation of chrome OS :).
