### ISSUE TITLE
What would it take to create a terminal for this?

### ISSUE THREAD

**Issue by mjarkk** [sebanc/brioche#5]
I'm very much liking this script so far and i'm kinda thinking to do real work using this tool.  
Though i'm kinda already getting tired of running `ctrl` + `alt` + `t` > `shell` > `brioche ubuntu shell` to get into a shell.  
So i was thinking it would be nice if there was a second terminal app just like the already existing terminal for linux.  

It looks like you're not very much interested in looking into this if i understand the support section in the readme.  
So i wanted to inspect this myself but i i'm still very new to Chrome OS and i think i need some pointing in the right direction to  get started.  
Sooo i wanted to ask if you know any of these:
- Is this even possible to create a second terminal application (is it even a app i can have multiple of)?
- Is there source code of the current linux terminal?
- Where can i find the terminal binary, icon, etc in the chrome os linux?

**Comment by sebanc** [comment]
I actually looked into this but the Crostini (terminal app + how it deals with icons notably) is a very complex setup not easily reproducible from brioche.

Most of the tools needed for crostini (notably garcon: https://chromium.googlesource.com/chromiumos/platform2/+/master/vm_tools/garcon/) are built into the "termina" vm and are therefore not accessible from brioche.

To have a better understanding of how it works, you might want to read this https://chromium.googlesource.com/chromiumos/docs/+/8c8ac04aed5d45bb6a14605c422dbbd01eeadf15/containers_and_vms.md and have a look at the termina vm content

**Comment by mjarkk** [comment]
That's a bummer it's such a complex setup.  

But it's probably not impossible :),  
I'll read up on what you send and see if i can learn some new things and maybe also start creating some new things.  

Thanks!
