### ISSUE TITLE
How uch does it takes time ?

### ISSUE THREAD

**Issue by yegender124001** [sebanc/brioche#9]
Hey @sebanc, How much time does it take in installing & How much it downloads?

I have a google hatch image

4GB Ram

i3 2nd generation processor
I am stuck here:
![image](https://user-images.githubusercontent.com/57976250/103651403-8aa23e80-4f87-11eb-8293-8f6026e60270.png)

**Comment by iknoors** [comment]
intel i5 120 gb nvme ssd surface pro 3rd gen took a while to install maybe 30 minutes
